name: ci

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

env:
  DOCKER_IMAGE: panchesco13/banknote-classifier
  TAG: ${{ github.event.client_payload.sha || github.sha }}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker compose build
          docker push ${DOCKER_IMAGE}:${TAG}

      - name: Trigger CD pipeline
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: maxim-panchuk/mlops_3
          event-type: cd-trigger
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
